export const SEARCH_TEST = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/cGnaZm6EQOJESde3Vv4v53Zk4gN.jpg',
      genre_ids: [18, 35],
      id: 626735,
      original_language: 'en',
      original_title: 'Dog',
      overview:
        "An army ranger and his dog embark on a road trip along the Pacific Coast Highway to attend a friend's funeral.",
      popularity: 113.832,
      poster_path: '/zHQy4h36WwuCetKS7C3wcT1hkgA.jpg',
      release_date: '2022-02-17',
      title: 'Dog',
      video: false,
      vote_average: 7.361,
      vote_count: 1180,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [27],
      id: 30362,
      original_language: 'en',
      original_title: 'Dog',
      overview: '',
      popularity: 1.894,
      poster_path: null,
      release_date: '2009-04-24',
      title: 'Dog',
      video: false,
      vote_average: 0.0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [18],
      id: 231218,
      original_language: 'en',
      original_title: 'Dog',
      overview:
        "A teenage girl gets ready to go out to meet her boyfriend, despite her mother's loud verbal disapproval of her clothes. She goes out to a deserted area with him and he begins to touch her up and have sex with her, however a dog reveals the true nature of her boyfriend.",
      popularity: 1.75,
      poster_path: '/8vvJwtpmqTwAkpDNHfGsphVNxYi.jpg',
      release_date: '2001-08-16',
      title: 'Dog',
      video: false,
      vote_average: 6.8,
      vote_count: 27,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [18],
      id: 1038113,
      original_language: 'fa',
      original_title: 'Dog',
      overview:
        'While driving and filming the landscapes around the road with his cellphone, the clergyman suddenly encounters a drug checkpoint. Officers want to inspect his car with a dog, but he does not allow it because he religiously believes that the dogs are unclean. He crashes on the way. A dog finds him on the road and tries to rescue him, but it does not succeed. Suddenly, his turban falls to the ground. The dog picks it up, puts it in the middle of the road, lies next to it, and waits for help.',
      popularity: 0.7,
      poster_path: '/k9r54dqYg5GZdBIO2KZ12G7Ob1v.jpg',
      release_date: '2021-09-18',
      title: 'Dog',
      video: false,
      vote_average: 0.0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: '/uljTV5en1IDNys7w7MLf5DAOTUD.jpg',
      genre_ids: [16, 35, 10402, 10751],
      id: 812204,
      original_language: 'en',
      original_title: 'Rock Dog 2: Rock Around the Park',
      overview:
        "When Bodi and his band 'True Blue' leave Snow Mountain, to tour with pop sensation, Lil' Foxy, they learn that fame comes at a price.",
      popularity: 30.315,
      poster_path: '/kETYRGA15L0wkVPugSl8lKmSgFn.jpg',
      release_date: '2021-08-05',
      title: 'Rock Dog 2: Rock Around the Park',
      video: false,
      vote_average: 6.695,
      vote_count: 95,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [16, 18],
      id: 123753,
      original_language: 'en',
      original_title: 'Dog',
      overview:
        "A young boy and his father live in a dull, lonely house with the shadow of mourning hanging over them both. The boy misses his mother but gets no comfort from his father's assertions that she went peacefully. This tragedy is added to by the family dog which is looking increasingly unhealthy.",
      popularity: 0.79,
      poster_path: '/1V3HCyoEwQbD1vhxISlm7F3rUua.jpg',
      release_date: '2001-08-01',
      title: 'Dog',
      video: false,
      vote_average: 6.5,
      vote_count: 14,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      id: 494422,
      original_language: 'en',
      original_title: 'Dog',
      overview:
        'United States / Mexico 1974, Super 8 transferred to digital, colour, silent, 3 min',
      popularity: 0.6,
      poster_path: '/30aotVEpqkoN5wdHr8J2ML47S76.jpg',
      release_date: '1974-12-24',
      title: 'Dog',
      video: false,
      vote_average: 0.0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [16],
      id: 1045937,
      original_language: 'en',
      original_title: 'Dog',
      overview: 'On how the dog was created',
      popularity: 0.6,
      poster_path: null,
      release_date: '1987-12-31',
      title: 'Dog',
      video: false,
      vote_average: 0.0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [16],
      id: 1054370,
      original_language: 'en',
      original_title: 'Dog',
      overview:
        'A young man comes to terms with his sexuality and confronts his bully in his home neighbourhood of Merton (London). Specially commissioned for the Southbank Festival of Neighbourhood 2013, adapted from the poem by Richard Scott.',
      popularity: 0.6,
      poster_path: null,
      release_date: '2013-09-30',
      title: 'Dog',
      video: false,
      vote_average: 0.0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: '/dNpAxKIAfkibLKkWRewewpnMatT.jpg',
      genre_ids: [18],
      id: 890971,
      original_language: 'el',
      original_title: '.dog',
      overview:
        'Young Dimitris, on the verge of manhood yet very much a child, has romanticized his imprisoned father to mythic proportions. When he gets released after ten years, Dimitris cannot wait to finally know him and make up for lost time. But when his father reveals his true nature, Dimitris must face a great dilemma: will his need of belonging prevail over his sense of justice?',
      popularity: 0.709,
      poster_path: '/3SCRCJvwtwZopxO2der0LExcOmu.jpg',
      release_date: '2021-11-09',
      title: '.dog',
      video: false,
      vote_average: 0.0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: '/1Wlwnhn5sXUIwlxpJgWszT622PS.jpg',
      genre_ids: [10751, 12, 35, 14],
      id: 585245,
      original_language: 'en',
      original_title: 'Clifford the Big Red Dog',
      overview:
        'As Emily struggles to fit in at home and at school, she discovers a small red puppy who is destined to become her best friend. When Clifford magically undergoes one heck of a growth spurt, becomes a gigantic dog and attracts the attention of a genetics company, Emily and her Uncle Casey have to fight the forces of greed as they go on the run across New York City. Along the way, Clifford affects the lives of everyone around him and teaches Emily and her uncle the true meaning of acceptance and unconditional love.',
      popularity: 124.271,
      poster_path: '/oifhfVhUcuDjE61V5bS5dfShQrm.jpg',
      release_date: '2021-11-10',
      title: 'Clifford the Big Red Dog',
      video: false,
      vote_average: 7.247,
      vote_count: 1540,
    },
    {
      adult: false,
      backdrop_path: '/hhDGtayED4HqhTrDRO4yqz9MVGG.jpg',
      genre_ids: [],
      id: 687558,
      original_language: 'ko',
      original_title: '여자전쟁:도기의난',
      overview:
        "There is a visitor for local herb gatherer Doggie who has no particular need or greed for anything. His friend Chang-guk who is wanted to failure in his business and his captivating wife Seon-hwa come to see Doggie who has no choice but to give them a place to hide. The three of them end up living umcomfortably together. Will Doggie be able to suppress his desires for his friend's wife? And what is her secret that Doggie must never know?",
      popularity: 26.526,
      poster_path: '/pUnZK0uumzFD068kdcHMBTj9YQq.jpg',
      release_date: '2016-03-24',
      title: "Female War: Doggie's Uprising",
      video: false,
      vote_average: 0.0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: '/vjnS4iu0SdwXm2LLqZGNCfpId9t.jpg',
      genre_ids: [16, 28, 35, 9648, 80, 14],
      id: 483455,
      original_language: 'ja',
      original_title: '文豪ストレイドッグス DEAD APPLE',
      overview:
        'A large scale catastrophe is occurring across the planet. Ability users are discovered after the appearance of a mysterious fog, apparently having committed suicide, so the Armed Detective Agency sets out to investigate these mysterious deaths. The case seems to involve an unknown ability user referred to as "Collector," a man who could be the mastermind behind the incident.\r Trust and courage are put to the test in order to save the city of Yokohama and ability users across the world from the grip of Collector where the Armed Detective Agency forms an unlikely partnership with the dangerous Port Mafia.',
      popularity: 24.85,
      poster_path: '/7ueB7Kxq2GObp5aDw6rsdzVefzP.jpg',
      release_date: '2018-03-03',
      title: 'Bungo Stray Dogs: Dead Apple',
      video: false,
      vote_average: 8.305,
      vote_count: 118,
    },
    {
      adult: false,
      backdrop_path: '/4AuJa4AoebEYC49BTJ1bwZv0Ey9.jpg',
      genre_ids: [10751, 10749],
      id: 583833,
      original_language: 'ru',
      original_title: 'Пальма',
      overview:
        "The film is inspired by an incredible story of a shepherd dog named Palm who was inadvertently left in the airport by her owner. She befriends nine-year old Nicholas whose mother dies leaving him with a father he barely knows - a pilot who finds the dog at the airport. It's a story of amazing adventures, true friendship and unconditional love.",
      popularity: 20.152,
      poster_path: '/3S3Mz9OD5SUwKy7kaqXcWAKUGXY.jpg',
      release_date: '2021-03-18',
      title: 'A Dog Named Palma',
      video: false,
      vote_average: 8.267,
      vote_count: 150,
    },
    {
      adult: false,
      backdrop_path: '/6PkzgNLKoK1Oy0j7L79JuBgl22r.jpg',
      genre_ids: [18, 36],
      id: 8588,
      original_language: 'en',
      original_title: 'Shooting Dogs',
      overview:
        'Two westerners, a priest and a teacher find themselves in the middle of the Rwandan genocide and face a moral dilemna. Do they place themselves in danger and protect the refugees, or escape the country with their lives? Based on a true story.',
      popularity: 8.113,
      poster_path: '/9xC2yUgqPVvoHykYuigrxLyunya.jpg',
      release_date: '2006-03-08',
      title: 'Shooting Dogs',
      video: false,
      vote_average: 7.453,
      vote_count: 118,
    },
    {
      adult: false,
      backdrop_path: '/89QZbysJM6bwwlYDa7NUytSQmWE.jpg',
      genre_ids: [16, 35, 12, 10751],
      id: 768726,
      original_language: 'es',
      original_title: "D'Artacán y los tres mosqueperros",
      overview:
        'France, 17th century, under the reign of Louis XIII. Dogtanian is an impetuous and innocent peasant from Gascony, as well as a skilled swordsman, who travels to Paris with the purpose of making his dream come true: to join the Corps of Muskehounds of the Royal Guard.',
      popularity: 14.25,
      poster_path: '/tzc6gzLENIujnRIx7rUjN1FIhn5.jpg',
      release_date: '2021-06-25',
      title: 'Dogtanian and the Three Muskehounds',
      video: false,
      vote_average: 6.8,
      vote_count: 100,
    },
    {
      adult: false,
      backdrop_path: '/cDhJZG5YgO1ldoczTWUc7rSWup3.jpg',
      genre_ids: [35, 10749],
      id: 21989,
      original_language: 'en',
      original_title: 'Hot Dog... The Movie',
      overview:
        "When a hopeful young American hot-dogger goes pole-to-pole with an arrogant Austrian pro, the snow really starts to fly! But as hot as it is on the mountain, it gets even hotter off when the pro's ex-girlfriend sets her eyes on the new blood. Who'll win the competition and the girl? Only a race to end all races can determine which skier can really cut the mustard!",
      popularity: 4.994,
      poster_path: '/qJ4tVNjjapCLigrVJi3ZXNX6xvB.jpg',
      release_date: '1984-01-13',
      title: 'Hot Dog... The Movie',
      video: false,
      vote_average: 4.6,
      vote_count: 54,
    },
    {
      adult: false,
      backdrop_path: '/uFzJtQncN5Od83UY0RCMu12SJHD.jpg',
      genre_ids: [18],
      id: 38810,
      original_language: 'el',
      original_title: 'Κυνόδοντας',
      overview:
        "Three teenagers are confined to an isolated country estate that could very well be on another planet. The trio spend their days listening to endless homemade tapes that teach them a whole new vocabulary. Any word that comes from beyond their family abode is instantly assigned a new meaning. Hence 'the sea' refers to a large armchair and 'zombies' are little yellow flowers. Having invented a brother whom they claim to have ostracized for his disobedience, the uber-controlling parents terrorize their offspring into submission.",
      popularity: 15.365,
      poster_path: '/7nLuUGlH12cegPfR84QX4xIIH9k.jpg',
      release_date: '2009-06-01',
      title: 'Dogtooth',
      video: false,
      vote_average: 7.122,
      vote_count: 1853,
    },
    {
      adult: false,
      backdrop_path: '/26LIw3oKGPUEGUpb8AXZ64dZZt8.jpg',
      genre_ids: [16, 35, 9648, 10751, 14],
      id: 843906,
      original_language: 'en',
      original_title:
        'Straight Outta Nowhere: Scooby-Doo! Meets Courage the Cowardly Dog',
      overview:
        'With Mystery, Inc. on the tail of a strange object in Nowhere, Kansas, the strange hometown of Eustice, Muriel, and Courage, the gang soon find themselves contending with a giant cicada monster and her winged warriors.',
      popularity: 47.847,
      poster_path: '/rlQJnQfPgaSGQtyMw35VOIqoIsj.jpg',
      release_date: '2021-09-14',
      title:
        'Straight Outta Nowhere: Scooby-Doo! Meets Courage the Cowardly Dog',
      video: false,
      vote_average: 7.927,
      vote_count: 342,
    },
    {
      adult: false,
      backdrop_path: '/jxEdvdiBpEevKiCWidpwRvDK2LY.jpg',
      genre_ids: [35, 18, 14],
      id: 40096,
      original_language: 'pt',
      original_title: 'O Auto da Compadecida',
      overview:
        'The lively João Grilo and the sly Chicó are poor guys living in the hinterland who cheat a bunch of people in a small in Northeastern Brazil. When they die, they have to be judged by Christ, the Devil and the Virgin Mary before they are admitted to paradise.',
      popularity: 10.696,
      poster_path: '/imcOp1kJsCsAFCoOtY5OnPrFbAf.jpg',
      release_date: '2000-09-15',
      title: "A Dog's Will",
      video: false,
      vote_average: 8.387,
      vote_count: 976,
    },
  ],
  total_pages: 119,
  total_results: 2369,
};
